const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','access-control-allow-origin':'*','access-control-allow-credentials':'true',...headers}});
const id=()=>crypto.randomUUID();
const enc=new TextEncoder();
async function hash(p){const b=await crypto.subtle.digest('SHA-256',enc.encode(p));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function readBody(r){try{return await r.json()}catch{return {}}}
function cookie(name,value,maxAge=604800){return `${name}=${value}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`}
async function userFrom(req,env){const c=req.headers.get('Cookie')||'';const m=c.match(/vt_session=([^;]+)/);if(!m)return null;return env.DB.prepare('SELECT u.id,u.email,u.name,u.location,u.nationality,u.religion,u.language,u.bio,u.photo_url,u.public_religion,u.public_location,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>datetime(\'now\')').bind(m[1]).first()}
async function requireAdmin(req,env){const u=await userFrom(req,env);if(!u||u.role!=='admin')throw new Error('Admin access required');return u}
function driveEmbed(url){if(!url)return url;const m=url.match(/\/d\/([a-zA-Z0-9_-]+)/);return m?`https://drive.google.com/uc?export=view&id=${m[1]}`:url}
export default {async fetch(req,env){const url=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'Content-Type','access-control-allow-credentials':'true'}});try{
if(url.pathname==='/api/public'&&req.method==='GET'){const [stories,gallery,team]=await Promise.all([env.DB.prepare("SELECT id,title,writer_name,writer_location,body,image_url,audio_url,video_url,published_at FROM stories WHERE status='published' ORDER BY published_at DESC LIMIT 50").all(),env.DB.prepare('SELECT * FROM gallery_items ORDER BY sort_order,created_at DESC LIMIT 100').all(),env.DB.prepare('SELECT * FROM team_members ORDER BY sort_order,created_at').all()]);return json({stories:stories.results,gallery:gallery.results,team:team.results})}
if(url.pathname.startsWith('/api/stories/')&&req.method==='GET'){const s=await env.DB.prepare("SELECT id,title,writer_name,writer_location,body,image_url,audio_url,video_url,published_at FROM stories WHERE id=? AND status='published'").bind(url.pathname.split('/').pop()).first();return s?json({story:s}):json({error:'Not found'},404)}
if(url.pathname==='/api/auth/register'&&req.method==='POST'){const b=await readBody(req);if(!b.email||!b.password||!b.name||b.password.length<8)return json({error:'Name, email and an 8+ character password are required.'},400);const exists=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(b.email.toLowerCase()).first();if(exists)return json({error:'Email already registered.'},409);const uid=id();await env.DB.prepare('INSERT INTO users(id,email,password_hash,name,location,nationality,language,bio,public_location) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid,b.email.toLowerCase(),await hash(b.password),b.name,b.location||null,b.nationality||null,b.language||null,b.bio||null,b.public_location?1:0).run();const sid=id();await env.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,datetime('now','+7 days'))").bind(sid,uid).run();return json({ok:true,user:{id:uid,name:b.name,email:b.email}},200,{ 'set-cookie':cookie('vt_session',sid)})}
if(url.pathname==='/api/auth/login'&&req.method==='POST'){const b=await readBody(req);const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind((b.email||'').toLowerCase()).first();if(!u||u.password_hash!==await hash(b.password||''))return json({error:'Invalid email or password.'},401);const sid=id();await env.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,datetime('now','+7 days'))").bind(sid,u.id).run();return json({ok:true,user:{id:u.id,name:u.name,email:u.email,role:u.role}},200,{'set-cookie':cookie('vt_session',sid)})}
if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const u=await userFrom(req,env);if(u){const c=req.headers.get('Cookie')||'';const m=c.match(/vt_session=([^;]+)/);if(m)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(m[1]).run()}return json({ok:true},200,{'set-cookie':cookie('vt_session','',0)})}
if(url.pathname==='/api/auth/me'&&req.method==='GET'){const u=await userFrom(req,env);return u?json({user:u}):json({error:'Not authenticated'},401)}
if(url.pathname==='/api/stories'&&req.method==='POST'){const u=await userFrom(req,env);if(!u)return json({error:'Login required'},401);const b=await readBody(req);if(!b.title||!b.body)return json({error:'Title and story text are required.'},400);const sid=id();await env.DB.prepare('INSERT INTO stories(id,title,writer_id,writer_name,writer_location,body,image_url,audio_url,video_url,status) VALUES(?,?,?,?,?,?,?,?,?,\'pending\')').bind(sid,b.title,u.id,u.name,u.location||null,b.body,driveEmbed(b.image_url)||null,driveEmbed(b.audio_url)||null,driveEmbed(b.video_url)||null).run();return json({ok:true,id:sid})}
if(url.pathname==='/api/admin/stories'&&req.method==='GET'){await requireAdmin(req,env);const r=await env.DB.prepare('SELECT * FROM stories ORDER BY created_at DESC').all();return json(r)}
if(url.pathname==='/api/admin/stories'&&req.method==='POST'){await requireAdmin(req,env);const b=await readBody(req);if(!b.title||!b.writer_name||!b.body)return json({error:'Title, writer and body are required.'},400);const sid=id();await env.DB.prepare('INSERT INTO stories(id,title,writer_name,writer_location,body,image_url,audio_url,video_url,status,published_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(sid,b.title,b.writer_name,b.writer_location||null,b.body,driveEmbed(b.image_url)||null,driveEmbed(b.audio_url)||null,driveEmbed(b.video_url)||null,b.status||'published',b.status==='published'?new Date().toISOString():null).run();return json({ok:true,id:sid})}
if(url.pathname.startsWith('/api/admin/stories/')&&req.method==='PUT'){await requireAdmin(req,env);const sid=url.pathname.split('/').pop();const b=await readBody(req);const published=b.status==='published'?new Date().toISOString():null;await env.DB.prepare('UPDATE stories SET status=?,featured=?,published_at=CASE WHEN ?=\'published\' THEN ? ELSE published_at END WHERE id=?').bind(b.status,b.featured?1:0,b.status,published,sid).run();return json({ok:true})}
if(url.pathname==='/api/admin/team'&&req.method==='GET'){await requireAdmin(req,env);return json(await env.DB.prepare('SELECT * FROM team_members ORDER BY sort_order,created_at').all())}
if(url.pathname==='/api/admin/team'&&req.method==='POST'){await requireAdmin(req,env);const b=await readBody(req);const mid=id();await env.DB.prepare('INSERT INTO team_members(id,name,position,bio,photo_url,sort_order) VALUES(?,?,?,?,?,?)').bind(mid,b.name,b.position,b.bio||null,driveEmbed(b.photo_url)||null,Number(b.sort_order)||0).run();return json({ok:true,id:mid})}
if(url.pathname.startsWith('/api/admin/team/')&&req.method==='DELETE'){await requireAdmin(req,env);await env.DB.prepare('DELETE FROM team_members WHERE id=?').bind(url.pathname.split('/').pop()).run();return json({ok:true})}
if(url.pathname==='/api/admin/gallery'&&req.method==='GET'){await requireAdmin(req,env);return json(await env.DB.prepare('SELECT * FROM gallery_items ORDER BY sort_order,created_at DESC').all())}
if(url.pathname==='/api/admin/gallery'&&req.method==='POST'){await requireAdmin(req,env);const b=await readBody(req);const gid=id();await env.DB.prepare('INSERT INTO gallery_items(id,title,image_url,caption,sort_order) VALUES(?,?,?,?,?)').bind(gid,b.title||null,driveEmbed(b.image_url),b.caption||null,Number(b.sort_order)||0).run();return json({ok:true,id:gid})}
if(url.pathname.startsWith('/api/admin/gallery/')&&req.method==='DELETE'){await requireAdmin(req,env);await env.DB.prepare('DELETE FROM gallery_items WHERE id=?').bind(url.pathname.split('/').pop()).run();return json({ok:true})}
return json({error:'Not found'},404)
}catch(e){return json({error:e.message||'Server error'},500)}}}
